"""Build a single-file FreeCAD macro from modular KT-aura sources.

This keeps source files split for maintainability while producing one
self-contained macro for easy import in FreeCAD.
"""

import os
import re


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_PATH = os.path.join(SCRIPT_DIR, "aura_config.py")
MACRO_SRC_PATH = os.path.join(SCRIPT_DIR, "sanctifiers_aura_aids.py")
MACRO_OUT_PATH = os.path.join(SCRIPT_DIR, "sanctifiers_aura_aids_macro.py")


def _read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def _strip_config_import_block(macro_src):
    pattern = re.compile(
        r"\nfrom aura_config import \(  # noqa: E402\n(?:\s{4}.+\n)+\)\n",
        re.MULTILINE,
    )
    return pattern.sub("\n", macro_src, count=1)


def build():
    config_src = _read(CONFIG_PATH).strip()
    macro_src = _read(MACRO_SRC_PATH)
    macro_src = _strip_config_import_block(macro_src).strip()

    bundled = (
        "\"\"\"Single-file FreeCAD macro generated from aura_config.py and "
        "sanctifiers_aura_aids.py.\n\n"
        "Do not edit this file directly; edit source files and re-run "
        "build_single_macro.py.\n"
        "\"\"\"\n\n"
        "# --- Embedded configuration ---\n"
        f"{config_src}\n\n"
        "# --- Embedded macro implementation ---\n"
        f"{macro_src}\n"
    )

    with open(MACRO_OUT_PATH, "w", encoding="utf-8") as f:
        f.write(bundled)

    print(f"Built single-file macro: {MACRO_OUT_PATH}")


if __name__ == "__main__":
    build()
