"""Single-file FreeCAD macro generated from aura_config.py and sanctifiers_aura_aids.py.

Do not edit this file directly; edit source files and re-run build_single_macro.py.
"""

# --- Embedded configuration ---
"""Parametric configuration for Kill Team aura aids.

This file is pure Python so both the FreeCAD macro and the diagram generator
can read the same values.
"""

from dataclasses import dataclass
from typing import Optional

# Printer build plate (Bambu Lab P2S)
BUILD_PLATE_X_MM = 256.0
BUILD_PLATE_Y_MM = 256.0
BUILD_PLATE_MARGIN_MM = 4.0

# Output modes
GENERATE_PRINT_LAYOUT = True
GENERATE_ASSEMBLY_PREVIEW = False
ASSEMBLY_PREVIEW_OFFSET_X_MM = -420.0
ASSEMBLY_PREVIEW_SPACING_Y_MM = 80.0
PRINT_LAYOUT_AID_GAP_Y_MM = 24.0

# Unit conversion
MM_PER_INCH = 25.4


@dataclass(frozen=True)
class HandleSpec:
    style: str = "low_profile_knob"
    hub_radius_mm: float = 9.0
    hub_thickness_mm: float = 3.2
    knob_radius_mm: float = 7.0
    knob_height_mm: float = 11.0
    loop_inner_radius_mm: float = 6.0
    loop_thickness_mm: float = 3.0
    loop_height_mm: float = 14.0
    tbar_length_mm: float = 18.0
    tbar_thickness_mm: float = 4.0
    tbar_post_radius_mm: float = 3.0
    tbar_post_height_mm: float = 11.0


@dataclass(frozen=True)
class ConnectorSpec:
    assembly_style: str = "press_fit_tabs"
    tab_width_mm: float = 5.6
    tab_length_mm: float = 4.2
    tab_clearance_mm: float = 0.25
    fit_preset: str = "medium"


@dataclass(frozen=True)
class AuraAidSpec:
    name: str
    short_label: str
    base_diameter_mm: float
    aura_range_in: float
    ring_thickness_mm: float = 2.4
    center_clearance_radial_mm: float = 1.0
    spoke_width_mm: float = 5.0
    center_spoke_count: int = 6
    ring_window_count: int = 36
    ring_window_ratio: float = 0.62
    ring_rail_mm: float = 1.2
    outer_rail_mm: Optional[float] = None
    force_split_segments: Optional[int] = None


HANDLE_STYLE = "low_profile_knob"

HANDLE_PRESETS = {
    "low_profile_knob": HandleSpec(
        style="low_profile_knob",
        hub_radius_mm=9.0,
        hub_thickness_mm=3.2,
        knob_radius_mm=7.0,
        knob_height_mm=11.0,
    ),
    "loop_handle": HandleSpec(
        style="loop_handle",
        hub_radius_mm=9.0,
        hub_thickness_mm=3.2,
        knob_radius_mm=6.0,
        knob_height_mm=8.0,
        loop_inner_radius_mm=6.5,
        loop_thickness_mm=3.0,
        loop_height_mm=15.0,
    ),
    "t_bar": HandleSpec(
        style="t_bar",
        hub_radius_mm=9.0,
        hub_thickness_mm=3.2,
        knob_radius_mm=6.0,
        knob_height_mm=8.0,
        tbar_length_mm=18.0,
        tbar_thickness_mm=4.0,
        tbar_post_radius_mm=3.0,
        tbar_post_height_mm=11.0,
    ),
}

HANDLE = HANDLE_PRESETS[HANDLE_STYLE]

CONNECTOR_TOLERANCE_PRESETS = {
    "tight": 0.18,
    "medium": 0.25,
    "loose": 0.33,
}

CONNECTOR_FIT_PRESET = "medium"

CONNECTOR = ConnectorSpec(
    assembly_style="press_fit_tabs",
    tab_width_mm=5.6,
    tab_length_mm=4.2,
    tab_clearance_mm=CONNECTOR_TOLERANCE_PRESETS[CONNECTOR_FIT_PRESET],
    fit_preset=CONNECTOR_FIT_PRESET,
)

ENABLE_PART_LABELS = False
PART_LABEL_TEXT_SIZE_MM = 3.2
PART_LABEL_RAISE_MM = 0.5
PART_LABEL_FONT_CANDIDATES = [
    "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
    "/System/Library/Fonts/Supplemental/Arial.ttf",
    "/System/Library/Fonts/Helvetica.ttc",
]

# Requested Sanctifiers aids.
AURA_AIDS: list[AuraAidSpec] = [
    AuraAidSpec(
        name="sanctifiers_aura_6in_32mm_base",
        short_label="S6-32",
        base_diameter_mm=32.0,
        aura_range_in=6.0,
        spoke_width_mm=4.0,
        center_spoke_count=8,
        ring_window_count=48,
        ring_window_ratio=0.72,
        outer_rail_mm=1.6,
        force_split_segments=4,
    ),
    AuraAidSpec(
        name="sanctifiers_aura_3in_25mm_base",
        short_label="S3-25",
        base_diameter_mm=25.0,
        aura_range_in=3.0,
        spoke_width_mm=4.0,
        center_spoke_count=6,
        ring_window_count=30,
        ring_window_ratio=0.70,
        force_split_segments=None,
    ),
]

# --- Embedded macro implementation ---
import math
import os
import sys

import FreeCAD as App
import Part


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__)) if "__file__" in globals() else os.getcwd()
if SCRIPT_DIR not in sys.path:
    sys.path.append(SCRIPT_DIR)


DOC_NAME = "KillTeamAuraAids"

doc = App.getDocument(DOC_NAME) if DOC_NAME in [d.Name for d in App.listDocuments().values()] else App.newDocument(DOC_NAME)

_LABEL_FONT_PATH = None
_LABEL_FONT_WARNED = False
_PREVIEW_CURSOR_Y = 0.0
_PRINT_CURSOR_Y = BUILD_PLATE_MARGIN_MM


def _safe_name(name):
    return "".join(ch if (ch.isalnum() or ch == "_") else "_" for ch in name)


def _aura_range_mm(aura_range_in):
    return aura_range_in * MM_PER_INCH


def _outer_radius_mm(base_diameter_mm, aura_range_in):
    return (base_diameter_mm / 2.0) + _aura_range_mm(aura_range_in)


def _inner_radius_mm(base_diameter_mm, clearance_radial_mm):
    return (base_diameter_mm / 2.0) + clearance_radial_mm


def _chord_length(radius, segment_count):
    return 2.0 * radius * math.sin(math.pi / segment_count)


def _segment_count_for_plate(outer_radius):
    max_span = min(BUILD_PLATE_X_MM, BUILD_PLATE_Y_MM) - (2.0 * BUILD_PLATE_MARGIN_MM)
    if (2.0 * outer_radius) <= max_span:
        return 1

    for n in range(2, 25):
        if _chord_length(outer_radius, n) <= max_span:
            return n
    raise ValueError("Could not find a printable segment count under 24 pieces.")


def _make_annulus(inner_r, outer_r, thickness):
    outer = Part.makeCylinder(outer_r, thickness)
    inner = Part.makeCylinder(inner_r, thickness)
    return outer.cut(inner)


def _make_sector_prism(radius, start_deg, end_deg, thickness):
    a0 = math.radians(start_deg)
    a1 = math.radians(end_deg)

    p0 = App.Vector(0, 0, 0)
    p1 = App.Vector(radius * math.cos(a0), radius * math.sin(a0), 0)
    p2 = App.Vector(radius * math.cos(a1), radius * math.sin(a1), 0)

    # Build a true circular sector (two radial edges + one arc edge).
    line_1 = Part.makeLine(p0, p1)
    arc = Part.makeCircle(radius, App.Vector(0, 0, 0), App.Vector(0, 0, 1), start_deg, end_deg)
    line_2 = Part.makeLine(p2, p0)

    wire = Part.Wire([line_1, arc, line_2])
    face = Part.Face(wire)
    return face.extrude(App.Vector(0, 0, thickness))


def _resolve_font_path():
    global _LABEL_FONT_PATH

    if _LABEL_FONT_PATH:
        return _LABEL_FONT_PATH

    for font_path in PART_LABEL_FONT_CANDIDATES:
        if os.path.exists(font_path):
            _LABEL_FONT_PATH = font_path
            return _LABEL_FONT_PATH
    return None


def _make_shapestring_shape(text, size, font_path):
    import Draft

    ss = Draft.make_shapestring(String=text, FontFile=font_path, Size=size, Tracking=0.0)
    doc.recompute()
    shape = ss.Shape.copy()
    doc.removeObject(ss.Name)
    return shape


def _label_shape(shape, label_text):
    global _LABEL_FONT_WARNED

    if not ENABLE_PART_LABELS:
        return shape

    font_path = _resolve_font_path()
    if not font_path:
        if not _LABEL_FONT_WARNED:
            App.Console.PrintWarning("No font found for part labels. Skipping labels.\n")
            _LABEL_FONT_WARNED = True
        return shape

    try:
        text_shape = _make_shapestring_shape(label_text, PART_LABEL_TEXT_SIZE_MM, font_path)
    except Exception as ex:
        if not _LABEL_FONT_WARNED:
            App.Console.PrintWarning(f"Unable to build part labels: {ex}\n")
            _LABEL_FONT_WARNED = True
        return shape

    bb = text_shape.BoundBox
    target = shape.BoundBox
    if bb.XLength <= 0 or bb.YLength <= 0:
        return shape

    tx = target.XMin + (target.XLength - bb.XLength) / 2.0 - bb.XMin
    ty = target.YMin + (target.YLength - bb.YLength) / 2.0 - bb.YMin
    tz = target.ZMax
    text_shape.translate(App.Vector(tx, ty, tz))

    solids = [face.extrude(App.Vector(0, 0, PART_LABEL_RAISE_MM)) for face in text_shape.Faces]
    if not solids:
        return shape

    text_compound = Part.makeCompound(solids)
    return shape.fuse(text_compound)


def _make_open_ring(inner_r, outer_r, thickness, window_count, window_ratio, rail_mm):
    return _make_open_ring_with_rails(
        inner_r=inner_r,
        outer_r=outer_r,
        thickness=thickness,
        window_count=window_count,
        window_ratio=window_ratio,
        inner_rail_mm=rail_mm,
        outer_rail_mm=rail_mm,
    )


def _make_open_ring_with_rails(inner_r, outer_r, thickness, window_count, window_ratio, inner_rail_mm, outer_rail_mm):
    ring = _make_annulus(inner_r, outer_r, thickness)

    if window_count <= 0 or window_ratio <= 0:
        return ring

    window_inner = inner_r + inner_rail_mm
    window_outer = outer_r - outer_rail_mm
    if window_outer <= window_inner:
        return ring

    bucket_angle = 360.0 / window_count
    window_angle = bucket_angle * min(max(window_ratio, 0.0), 0.95)

    for i in range(window_count):
        center_deg = i * bucket_angle
        start_deg = center_deg - (window_angle / 2.0)
        end_deg = center_deg + (window_angle / 2.0)

        win_annulus = _make_annulus(window_inner, window_outer, thickness + 0.2)
        win_annulus.translate(App.Vector(0, 0, -0.1))
        win_sector = _make_sector_prism(window_outer + 0.6, start_deg, end_deg, thickness + 0.2)
        win_sector.translate(App.Vector(0, 0, -0.1))

        ring = ring.cut(win_annulus.common(win_sector))

    return ring


def _make_spoke(hub_radius, inner_radius, spoke_width, thickness, angle_deg):
    span = inner_radius - hub_radius
    if span <= 0:
        return None

    spoke = Part.makeBox(span, spoke_width, thickness)
    spoke.translate(App.Vector(hub_radius, -spoke_width / 2.0, 0))
    spoke.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), angle_deg)
    return spoke


def _make_tab(hub_radius, tab_length, tab_width, thickness, angle_deg):
    tab = Part.makeBox(tab_length, tab_width, thickness)
    tab.translate(App.Vector(hub_radius - tab_length, -tab_width / 2.0, 0))
    tab.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), angle_deg)
    return tab


def _make_hub_with_handle(segment_count, total_thickness):
    hub = Part.makeCylinder(HANDLE.hub_radius_mm, HANDLE.hub_thickness_mm)

    if HANDLE.style == "loop_handle":
        major = HANDLE.loop_inner_radius_mm + (HANDLE.loop_thickness_mm / 2.0)
        minor = HANDLE.loop_thickness_mm / 2.0
        loop = Part.makeTorus(major, minor)
        loop.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
        loop.translate(App.Vector(0, 0, HANDLE.hub_thickness_mm + major))
        hub = hub.fuse(loop)
    elif HANDLE.style == "t_bar":
        post = Part.makeCylinder(HANDLE.tbar_post_radius_mm, HANDLE.tbar_post_height_mm)
        post.translate(App.Vector(0, 0, HANDLE.hub_thickness_mm))
        bar = Part.makeBox(HANDLE.tbar_length_mm, HANDLE.tbar_thickness_mm, HANDLE.tbar_thickness_mm)
        bar.translate(
            App.Vector(
                -HANDLE.tbar_length_mm / 2.0,
                -HANDLE.tbar_thickness_mm / 2.0,
                HANDLE.hub_thickness_mm + HANDLE.tbar_post_height_mm,
            )
        )
        hub = hub.fuse(post).fuse(bar)
    else:
        knob = Part.makeCylinder(HANDLE.knob_radius_mm, HANDLE.knob_height_mm)
        knob.translate(App.Vector(0, 0, HANDLE.hub_thickness_mm))
        hub = hub.fuse(knob)

    if segment_count > 1 and CONNECTOR.assembly_style == "press_fit_tabs":
        slot_w = CONNECTOR.tab_width_mm + CONNECTOR.tab_clearance_mm
        slot_l = CONNECTOR.tab_length_mm + CONNECTOR.tab_clearance_mm
        for i in range(segment_count):
            ang = (360.0 / segment_count) * i + (180.0 / segment_count)
            slot = Part.makeBox(slot_l, slot_w, total_thickness + 0.2)
            slot.translate(App.Vector(HANDLE.hub_radius_mm - slot_l, -slot_w / 2.0, -0.1))
            slot.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), ang)
            hub = hub.cut(slot)

    return hub


def _build_single_piece_aid(spec, inner_r, outer_r, thickness):
    outer_rail_mm = spec.outer_rail_mm if spec.outer_rail_mm is not None else spec.ring_rail_mm
    ring = _make_open_ring_with_rails(
        inner_r=inner_r,
        outer_r=outer_r,
        thickness=thickness,
        window_count=spec.ring_window_count,
        window_ratio=spec.ring_window_ratio,
        inner_rail_mm=spec.ring_rail_mm,
        outer_rail_mm=outer_rail_mm,
    )

    spoke_count = max(3, spec.center_spoke_count)
    angles = [i * (360.0 / spoke_count) for i in range(spoke_count)]

    for angle in angles:
        spoke = _make_spoke(HANDLE.hub_radius_mm, inner_r, spec.spoke_width_mm, thickness, angle)
        if spoke is not None:
            ring = ring.fuse(spoke)

    hub = _make_hub_with_handle(segment_count=1, total_thickness=thickness)
    return ring.fuse(hub)


def _build_segmented_aid(spec, inner_r, outer_r, thickness, segment_count, spoke_width):
    # Build one full curved/open ring structure first (same design language as
    # single-piece aid), then chop it into printable sectors.
    outer_rail_mm = spec.outer_rail_mm if spec.outer_rail_mm is not None else spec.ring_rail_mm
    full_shape = _make_open_ring_with_rails(
        inner_r=inner_r,
        outer_r=outer_r,
        thickness=thickness,
        window_count=spec.ring_window_count,
        window_ratio=spec.ring_window_ratio,
        inner_rail_mm=spec.ring_rail_mm,
        outer_rail_mm=outer_rail_mm,
    )

    spoke_count = max(3, spec.center_spoke_count)
    full_spoke_angles = [i * (360.0 / spoke_count) for i in range(spoke_count)]
    for angle in full_spoke_angles:
        spoke = _make_spoke(HANDLE.hub_radius_mm, inner_r, spoke_width, thickness, angle)
        if spoke is not None:
            full_shape = full_shape.fuse(spoke)

    segment_angle = 360.0 / segment_count

    segments = []
    for i in range(segment_count):
        start_deg = i * segment_angle
        end_deg = (i + 1) * segment_angle
        mid_deg = start_deg + (segment_angle / 2.0)

        sector = _make_sector_prism(outer_r + 1.0, start_deg, end_deg, thickness)
        seg_shape = full_shape.common(sector)

        if CONNECTOR.assembly_style == "press_fit_tabs":
            tab = _make_tab(
                HANDLE.hub_radius_mm,
                CONNECTOR.tab_length_mm,
                CONNECTOR.tab_width_mm,
                thickness,
                mid_deg,
            )
            seg_shape = seg_shape.fuse(tab)

        segments.append(seg_shape)

    hub = _make_hub_with_handle(segment_count=segment_count, total_thickness=thickness)
    return segments, hub


def _layout_shapes_for_print(shapes, spacing=12.0, start_y=None):
    cursor_x = 0.0
    cursor_y = 0.0
    row_h = 0.0

    max_x = BUILD_PLATE_X_MM - BUILD_PLATE_MARGIN_MM
    start_x = BUILD_PLATE_MARGIN_MM
    if start_y is None:
        start_y = BUILD_PLATE_MARGIN_MM

    cursor_x = start_x
    cursor_y = start_y

    laid_out = []
    max_y = start_y

    for shape in shapes:
        bb = shape.BoundBox
        w = bb.XLength
        h = bb.YLength

        if cursor_x + w > max_x:
            cursor_x = start_x
            cursor_y += row_h + spacing
            row_h = 0.0

        moved = shape.copy()
        moved.translate(App.Vector(cursor_x - bb.XMin, cursor_y - bb.YMin, 0))
        laid_out.append(moved)

        moved_bb = moved.BoundBox
        max_y = max(max_y, moved_bb.YMax)

        cursor_x += w + spacing
        row_h = max(row_h, h)

    next_start_y = max_y + PRINT_LAYOUT_AID_GAP_Y_MM
    return laid_out, next_start_y


def _translated(shape, x, y, z=0.0):
    moved = shape.copy()
    moved.translate(App.Vector(x, y, z))
    return moved


def build_aid(spec):
    global _PREVIEW_CURSOR_Y
    global _PRINT_CURSOR_Y

    outer_r = _outer_radius_mm(spec.base_diameter_mm, spec.aura_range_in)
    inner_r = _inner_radius_mm(spec.base_diameter_mm, spec.center_clearance_radial_mm)

    # Keep the gameplay distance invariant: base outer edge -> aura outer edge = aura_range_in.
    aura_target_mm = _aura_range_mm(spec.aura_range_in)
    aura_actual_mm = outer_r - (spec.base_diameter_mm / 2.0)
    if abs(aura_actual_mm - aura_target_mm) > 1e-6:
        raise ValueError(
            f"Aura distance mismatch for {spec.name}: expected {aura_target_mm:.3f}mm, got {aura_actual_mm:.3f}mm"
        )

    if inner_r >= outer_r:
        raise ValueError(f"Invalid radii for {spec.name}: inner radius >= outer radius")

    segment_count = spec.force_split_segments or _segment_count_for_plate(outer_r)

    shapes_for_layout = []
    if segment_count == 1:
        shapes_for_layout.append((_build_single_piece_aid(spec, inner_r, outer_r, spec.ring_thickness_mm), f"{spec.short_label}-P1"))
    else:
        segments, hub = _build_segmented_aid(
            spec=spec,
            inner_r=inner_r,
            outer_r=outer_r,
            thickness=spec.ring_thickness_mm,
            segment_count=segment_count,
            spoke_width=spec.spoke_width_mm,
        )
        for i, seg in enumerate(segments, start=1):
            shapes_for_layout.append((seg, f"{spec.short_label}-P{i}"))
        shapes_for_layout.append((hub, f"{spec.short_label}-H"))

    safe_prefix = _safe_name(spec.name)
    raw_shapes = [item[0] for item in shapes_for_layout]
    labels = [item[1] for item in shapes_for_layout]

    if GENERATE_ASSEMBLY_PREVIEW:
        preview_x = ASSEMBLY_PREVIEW_OFFSET_X_MM
        preview_y = _PREVIEW_CURSOR_Y
        for idx, raw_shape in enumerate(raw_shapes, start=1):
            preview_shape = _translated(raw_shape, preview_x, preview_y)
            obj = doc.addObject("Part::Feature", f"{safe_prefix}_preview_{idx}")
            obj.Shape = preview_shape
        _PREVIEW_CURSOR_Y += (2.0 * outer_r) + ASSEMBLY_PREVIEW_SPACING_Y_MM

    if GENERATE_PRINT_LAYOUT:
        laid_out_shapes, _PRINT_CURSOR_Y = _layout_shapes_for_print(raw_shapes, start_y=_PRINT_CURSOR_Y)
        for idx, laid_out in enumerate(laid_out_shapes, start=1):
            labeled_shape = _label_shape(laid_out, labels[idx - 1])
            obj = doc.addObject("Part::Feature", f"{safe_prefix}_part_{idx}")
            obj.Shape = labeled_shape

    App.Console.PrintMessage(
        f"Built {spec.name}: base={spec.base_diameter_mm:.1f}mm, aura={spec.aura_range_in:.1f}in, "
        f"outer_diameter={2.0 * outer_r:.1f}mm, segments={segment_count}, "
        f"windows={spec.ring_window_count}, handle={HANDLE.style}, fit={CONNECTOR.fit_preset}, "
        f"preview={'on' if GENERATE_ASSEMBLY_PREVIEW else 'off'}, print_layout={'on' if GENERATE_PRINT_LAYOUT else 'off'}\n"
    )


for aura in AURA_AIDS:
    build_aid(aura)


doc.recompute()

if "Gui" in globals():
    Gui.SendMsgToActiveView("ViewFit")
